version: '3.8'

services:
  app:
    build: .
    container_name: livraria-api
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_NAME=livraria
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - MONGO_URL=mongodb://mongo:27017/livraria
    ports:
      - "3000:3000"
    depends_on:
      - db
      - mongo
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: livraria
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  postgres-data:
  mongo-data:
